keywords = [
    "Linux",
    "Ubuntu",
    "Debian",
    "Servers",
    "Systems administration",
    "Command line",
    "SSH",
    "Firewall",
    "SELinux",
    "Docker",
    "Kubernetes",
    "Apache",
    "Nginx",
    "PHP",
    "Python",
    "MySQL",
    "ecommerce",
    "online shopping",
    "Magento",
    "WooCommerce",
    "OPCneCommerce",
    "Shopify",
    "web hosting",
    "VPS",
    "cloud hosting",
    "online store",
    "small business ecommerce",
    "startup ecommerce",
    "PCI compliance",
    "digital marketing",
    "SEO",
    "analytics",
    "email marketing",
]